//! Access to the embedded front-sprite blob (generated by tools/gen_assets.py).
//!
//! Layout per species: 8192 B RGB565 big-endian (64x64) followed by 512 B
//! alpha mask (one bit per pixel, MSB-first).

use embedded_graphics::pixelcolor::raw::RawU16;
use embedded_graphics::pixelcolor::Rgb565;

use crate::dex_data::SPRITE_STRIDE;

pub const SPRITE_SIZE: u32 = 64;
const RGB_LEN: usize = 8192;

static SPRITES: &[u8] = include_bytes!("../assets/sprites.bin");

pub struct Sprite {
    rgb: &'static [u8],
    mask: &'static [u8],
}

impl Sprite {
    /// `no` is the 1-based dex number.
    pub fn new(no: u16) -> Self {
        let base = (no as usize - 1) * SPRITE_STRIDE;
        let s = &SPRITES[base..base + SPRITE_STRIDE];
        Self {
            rgb: &s[..RGB_LEN],
            mask: &s[RGB_LEN..],
        }
    }

    #[inline]
    pub fn opaque(&self, x: u32, y: u32) -> bool {
        let i = (y * SPRITE_SIZE + x) as usize;
        self.mask[i >> 3] & (0x80 >> (i & 7)) != 0
    }

    #[inline]
    pub fn color(&self, x: u32, y: u32) -> Rgb565 {
        let i = ((y * SPRITE_SIZE + x) * 2) as usize;
        Rgb565::from(RawU16::new(u16::from_be_bytes([
            self.rgb[i],
            self.rgb[i + 1],
        ])))
    }
}
