//! Access to the embedded front-sprite blob (generated by tools/gen_assets.py).
//!
//! Layout per species: 32 B palette (16 x RGB565, big-endian — entry 0 is the
//! transparent index) followed by 2048 B of 4bpp indices, high nibble first.
//! GBA front sprites are 4bpp artwork, so storing them this way is lossless
//! (the generator asserts it) and keeps the blob at 0.8 MB instead of 3.4 MB —
//! which is what leaves room for the cries and BGM in flash.

use embedded_graphics::pixelcolor::raw::RawU16;
use embedded_graphics::pixelcolor::Rgb565;

use crate::dex_data::SPRITE_STRIDE;

pub const SPRITE_SIZE: u32 = 64;
/// Bytes of palette before the pixel indices start.
const PALETTE_LEN: usize = 32;

static SPRITES: &[u8] = include_bytes!("../assets/sprites.bin");

pub struct Sprite {
    data: &'static [u8],
}

impl Sprite {
    /// `no` is the 1-based dex number.
    pub fn new(no: u16) -> Self {
        let base = (no as usize - 1) * SPRITE_STRIDE;
        Self {
            data: &SPRITES[base..base + SPRITE_STRIDE],
        }
    }

    /// Palette index of one pixel; 0 means "no pixel here".
    #[inline]
    fn index(&self, x: u32, y: u32) -> u8 {
        let i = (y * SPRITE_SIZE + x) as usize;
        let b = self.data[PALETTE_LEN + (i >> 1)];
        if i & 1 == 0 {
            b >> 4
        } else {
            b & 0x0F
        }
    }

    #[inline]
    pub fn opaque(&self, x: u32, y: u32) -> bool {
        self.index(x, y) != 0
    }

    #[inline]
    pub fn color(&self, x: u32, y: u32) -> Rgb565 {
        let i = self.index(x, y) as usize * 2;
        Rgb565::from(RawU16::new(u16::from_be_bytes([
            self.data[i],
            self.data[i + 1],
        ])))
    }
}
