#!/usr/bin/env python3
"""Build the firmware font from Fusion Pixel 10px Monospaced BDF (OFL-1.1).

Source (hand-tuned for low-res screens, referenced by dotzuki):
  ~/develop/dotzuki/workspace/crates/dotzuki-renderer/fonts/
    fusion-pixel-10px-monospaced-{latin,zh_hans}.bdf   (read-only)

Input:  tools/charset.json {"chars": "..."} from gen_assets.py
Output: firmware/assets/font10.bin              glyph blobs, sorted by codepoint
        firmware/src/font_zh_data.rs            CP10 / OFF10 tables

Blob per glyph: u8 w, u8 h, i8 x_off, i8 y_off, u8 advance,
then ceil(w/8) * h row bytes, MSB-first (verbatim BDF BITMAP rows).
ASCII comes from the latin BDF (5px advance), CJK from zh_hans (10px).
"""

import json
import os
import re

ROOT = __file__.rsplit("/", 2)[0]
BDF_DIR = os.path.expanduser(
    "~/develop/dotzuki/workspace/crates/dotzuki-renderer/fonts"
)
LATIN = f"{BDF_DIR}/fusion-pixel-10px-monospaced-latin.bdf"
ZH = f"{BDF_DIR}/fusion-pixel-10px-monospaced-zh_hans.bdf"
CHARSET = f"{ROOT}/tools/charset.json"
NOTO = f"{ROOT}/tools/fonts/NotoSansCJKsc-Regular.otf"


def parse_bdf(path):
    glyphs = {}
    for block in re.finditer(
        r"STARTCHAR [^\n]*\nENCODING (\d+)\n(.*?)ENDCHAR", open(path, encoding="utf-8").read(), re.S
    ):
        cp = int(block.group(1))
        body = block.group(2)
        dwidth = int(re.search(r"DWIDTH (\d+)", body).group(1))
        bbx = re.search(r"BBX (-?\d+) (-?\d+) (-?\d+) (-?\d+)", body)
        w, h, x_off, y_off = map(int, bbx.groups())
        rows_hex = body.split("BITMAP\n", 1)[1].split()
        rows = bytes.fromhex("".join(rows_hex))
        glyphs[cp] = (w, h, x_off, y_off, dwidth, rows)
    return glyphs


def noto_fallback(ch: str):
    """Rasterize a glyph missing from the BDFs at 10px (rare chars)."""
    from PIL import ImageFont

    font = ImageFont.truetype(NOTO, 10)
    ascii_ch = ord(ch) < 128
    w = 5 if ascii_ch else 10
    mask = font.getmask(ch, mode="L")
    mw, mh = mask.size
    x0, y0 = (w - mw) // 2, (10 - mh) // 2
    rows = bytearray(((w + 7) // 8) * 10)
    for y in range(mh):
        for x in range(mw):
            px, py = x0 + x, y0 + y
            if 0 <= px < w and mask[y * mw + x] >= 128:
                rows[py * ((w + 7) // 8) + px // 8] |= 0x80 >> (px % 8)
    return (w, 10, 0, -1, w, bytes(rows))


def main() -> None:
    chars = sorted(set(json.load(open(CHARSET))["chars"]))
    latin = parse_bdf(LATIN)
    zh = parse_bdf(ZH)

    blob = bytearray()
    cps, offs = [], []
    fallbacks = []
    for ch in chars:
        cp = ord(ch)
        table = latin if cp < 128 else zh
        g = table.get(cp)
        if g is None:
            g = zh.get(cp) if cp < 128 else latin.get(cp)
        if g is None:
            g = noto_fallback(ch)
            fallbacks.append(ch)
        w, h, x_off, y_off, dwidth, rows = g
        assert len(rows) == ((w + 7) // 8) * h, f"bad bitmap len for {ch!r}"
        offs.append(len(blob))
        cps.append(cp)
        blob += bytes([w, h, x_off & 0xFF, y_off & 0xFF, dwidth]) + rows
    offs.append(len(blob))
    if fallbacks:
        print(f"Noto 10px fallback for: {fallbacks}")

    print(f"charset {len(chars)} glyphs, font10 {len(blob)} bytes")
    open(f"{ROOT}/firmware/assets/font10.bin", "wb").write(blob)
    with open(f"{ROOT}/firmware/src/font_zh_data.rs", "w") as f:
        f.write("// @generated by tools/gen_font.py — do not edit by hand.\n")
        f.write("// Fusion Pixel 10px Monospaced subset (OFL-1.1).\n")
        f.write("// Per glyph: u8 w,h, i8 x_off,y_off, u8 advance, then MSB-first rows.\n\n")
        f.write("pub static CP10: &[u16] = &[")
        f.write(",".join(str(c) for c in cps))
        f.write("];\n")
        f.write("pub static OFF10: &[u32] = &[")
        f.write(",".join(str(o) for o in offs))
        f.write("];\n")
        f.write('pub static B10: &[u8] = include_bytes!("../assets/font10.bin");\n')
    print("wrote firmware/src/font_zh_data.rs")


if __name__ == "__main__":
    main()
