#!/usr/bin/env python3
"""Generate pokedex firmware assets from open-pokefirered data (read-only).

Sources (never modified):
  ~/develop/open-pokefirered/firered/assets/pokedex.json         species base data
  ~/develop/open-pokefirered/firered/assets/pokedex_entries.json dex text / height / weight
  ~/develop/open-pokefirered/firered/assets/battle_fronts.bin    386 x 64x64 RGBA8888 front sprites
  ~/develop/open-pokefirered/firered/assets/battle_fronts.json   name -> byte offset
  unown_fronts.bin (form 'A' fallback for #201), pokemon_icons.bin (fallback for #360)

Outputs (into this repo only):
  firmware/assets/sprites.bin   386 x (8192B RGB565 + 512B alpha mask), MSB-first bits
  firmware/src/dex_data.rs      Rust static tables for the national dex (1..=386)

Known data gaps and fallbacks:
  - pokedex_entries.json misses CHIKORITA (#152) and TYRANITAR (#248):
    placeholder category/description/height/weight are emitted.
  - battle_fronts.bin misses UNOWN (#201) and CASTFORM (#360):
    UNOWN uses form 'A' from unown_fronts.bin; CASTFORM uses its 32x32
    menu icon (first frame) nearest-upsampled to 64x64.
"""

import json
import os
import sys

SRC = os.path.expanduser("~/develop/open-pokefirered/firered/assets")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_BIN = os.path.join(ROOT, "firmware", "assets", "sprites.bin")
OUT_RS = os.path.join(ROOT, "firmware", "src", "dex_data.rs")

DEX_COUNT = 386

TRANSLIT = {
    "é": "e",
    "É": "E",
    "♀": " F",
    "♂": " M",
    "\u2019": "'",
}


def clean_text(s: str) -> str:
    for k, v in TRANSLIT.items():
        s = s.replace(k, v)
    s = s.replace("_", " ")
    return " ".join(s.replace("\n", " ").split())


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def to_rgb565_mask(rgba: bytes) -> tuple[bytearray, bytearray]:
    px = bytearray(8192)
    mask = bytearray(512)
    for i in range(4096):
        r, g, b, a = rgba[4 * i : 4 * i + 4]
        if a:
            c = rgb565(r, g, b)
            px[2 * i] = c >> 8
            px[2 * i + 1] = c & 0xFF
            mask[i >> 3] |= 0x80 >> (i & 7)
    return px, mask


def main() -> None:
    pd = json.load(open(f"{SRC}/pokedex.json"))
    entries = json.load(open(f"{SRC}/pokedex_entries.json"))
    fronts = json.load(open(f"{SRC}/battle_fronts.bin".replace(".bin", ".json")))
    blob = open(f"{SRC}/battle_fronts.bin", "rb").read()
    unown = open(f"{SRC}/unown_fronts.bin", "rb").read()
    icons = open(f"{SRC}/pokemon_icons.bin", "rb").read()
    type_ids = pd["types"]
    species = pd["species"]

    rows = []
    sprites = bytearray()
    for no in range(1, DEX_COUNT + 1):
        sp = species[no]
        name = sp["name"]
        disp = clean_text(name)
        ent = entries.get(name)
        if ent is None:
            ent = {
                "category": "UNKNOWN",
                "desc": "No data recorded for this POKeMON.",
                "height": 0,
                "weight": 0,
            }

        t = [type_ids[x] for x in sp["types"]]
        t2 = t[1] if len(t) > 1 and t[1] != t[0] else 255

        off = fronts.get(name.lower())
        if off is not None:
            rgba = blob[off : off + 16384]
        elif name == "UNOWN":
            rgba = unown[0:16384]
        elif name == "CASTFORM":
            # 32x32 menu icon (first frame), nearest-upsampled to 64x64
            small = icons[no * 8192 : no * 8192 + 4096]
            rgba = bytearray(16384)
            for y in range(32):
                for x in range(32):
                    q = small[(y * 32 + x) * 4 : (y * 32 + x) * 4 + 4]
                    for dy in (0, 1):
                        for dx in (0, 1):
                            i = ((y * 2 + dy) * 64 + x * 2 + dx) * 4
                            rgba[i : i + 4] = q
        else:
            sys.exit(f"missing front sprite for #{no} {name}")

        px, mask = to_rgb565_mask(rgba)
        sprites += px + mask

        rows.append(
            dict(
                no=no,
                name=disp,
                category=clean_text(ent["category"]),
                t1=t[0],
                t2=t2,
                hp=sp["base_hp"],
                atk=sp["base_atk"],
                dfn=sp["base_def"],
                spa=sp["base_spatk"],
                spd=sp["base_spdef"],
                spe=sp["base_speed"],
                height=ent["height"],
                weight=ent["weight"],
                desc=clean_text(ent["desc"]),
            )
        )

    os.makedirs(os.path.dirname(OUT_BIN), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_RS), exist_ok=True)
    open(OUT_BIN, "wb").write(sprites)
    print(f"wrote {OUT_BIN} ({len(sprites)} bytes)")

    with open(OUT_RS, "w", encoding="utf-8") as f:
        f.write("// @generated by tools/gen_assets.py — do not edit by hand.\n")
        f.write("// Source: open-pokefirered (Pokemon FireRed) extracted data.\n")
        f.write("pub const DEX_LEN: usize = ")
        f.write(f"{DEX_COUNT};\n")
        f.write("pub const SPRITE_STRIDE: usize = 8704;\n\n")
        f.write("/// One species. `types` uses type ids; 255 = none.\n")
        f.write("#[allow(dead_code)]\n")
        f.write("pub struct DexEntry {\n")
        f.write("    pub no: u16,\n    pub name: &'static str,\n")
        f.write("    pub category: &'static str,\n    pub types: [u8; 2],\n")
        f.write("    /// HP, ATK, DEF, SPA, SPD, SPE\n    pub base: [u8; 6],\n")
        f.write("    pub height_dm: u8,\n    pub weight_hg: u16,\n")
        f.write("    pub desc: &'static str,\n}\n\n")
        f.write("pub static DEX: [DexEntry; DEX_LEN] = [\n")
        for r in rows:
            desc = r["desc"].replace("\\", "\\\\").replace('"', '\\"')
            f.write(
                f"    DexEntry {{ no: {r['no']}, name: \"{r['name']}\", "
                f"category: \"{r['category']}\", types: [{r['t1']}, {r['t2']}], "
                f"base: [{r['hp']}, {r['atk']}, {r['dfn']}, {r['spa']}, {r['spd']}, {r['spe']}], "
                f"height_dm: {r['height']}, weight_hg: {r['weight']}, "
                f"desc: \"{desc}\" }},\n"
            )
        f.write("];\n")
    print(f"wrote {OUT_RS} ({len(rows)} entries)")


if __name__ == "__main__":
    main()

